### ISSUE TITLE
affine-cloud api extract as openapi schema files

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/OctoBase#148]
As more and more developers look to connect affine data to other applications, you should consider a collection of apis that support placing affine on postman

**Comment by darkskygit** [comment]
In principle, octobase does not provide services based on http apis, which should belong to the function of affine cloud. Consideration should be given to providing `openapi schema`, rather than specifically adapted to postman.

**Comment by fundon** [comment]
See https://crates.io/search?q=openapi, [utoipa](https://crates.io/crates/utoipa) is probably the most active.

**Comment by darkskygit** [comment]
> See https://crates.io/search?q=openapi, [utoipa](https://crates.io/crates/utoipa) is probably the most active.

we are currently using utipa to produce openapi, easy to use.

**Comment by darkskygit** [comment]
fixed in #237
