### ISSUE TITLE
Support single file workspace import & export

### ISSUE THREAD

**Issue by doodlewind** [toeverything/OctoBase#173]
One basic design decision in our native client is to persistent the workspace content, including YDoc and blobs, into a single SQLite-based binary file (e.g., `my-workspace.db`). This allows for intuitive file management on user side and better data ownership.

Meanwhile, based on how CRDT works, when user opens this workspace file, we will automatically duplicate it into the native client data directory, using this implicitly-duplicated workspace file as the single source of truth (on top of our provider-based synchronization), and automatically *writes* to the original user-selected workspace file. This will make sure the user could always see and keep the latest version of their selected workspace.

@joebeijing will help with more product-side related requirement.

/cc @tzhangchi @HeJiachen-PM

**Comment by tzhangchi** [comment]
cc @pengx17

**Comment by joebeijing** [comment]
This issue will be followed up in https://github.com/toeverything/AFFiNE/issues/2488

**Comment by doodlewind** [comment]
Closed since the `.affine` format DB is support in AFFiNE
