### ISSUE TITLE
allow email register

### ISSUE THREAD

**Issue by darkskygit** [toeverything/OctoBase#183]

**Comment by water-in-stone** [comment]
I have 2 questions: 
1. Is it implemented in the current version of OctoBase?
2. Does it yet require implementation?

**Comment by darkskygit** [comment]
> I have 2 questions:
> 
> 1. Is it implemented in the current version of OctoBase?
> 2. Does it yet require implementation?

I have implemented this feature in the new affine server, the server logic is no longer included in the octobase repo, please go to the affine repo to check
