### ISSUE TITLE
jni sync disconnect after 1m

### ISSUE THREAD

**Issue by darkskygit** [toeverything/OctoBase#193]

**Comment by darkskygit** [comment]
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/25152247/220524303-0da8b32e-7e7f-4aa7-b1d2-98d1268c8b8c.png"> 
remote update has been applied, which may be a problem with the workspace cache

**Comment by thorseraq** [comment]
closed by https://github.com/toeverything/OctoBase/pull/221
