### ISSUE TITLE
abstract reduction in jwt

### ISSUE THREAD

**Issue by darkskygit** [toeverything/OctoBase#239]
In the original design, [jwt](https://github.com/toeverything/OctoBase/tree/master/apps/frontend/libs/jwt) will be responsible for docking multiple backends and supporting the export of different formats, so the data structure and API are abstracted in multiple layers.
At present, we have re-implemented (or plan to re-implement) these more complex logics in jwst using rust, and we need to streamline the abstraction of jwt to make it easier to use.
I plan to simplify the abstraction of jwt to a level similar to that of @blocksuite/store, but unlike @blocksuite/store, the interface provided by jwt can more flexibly construct block graphs that refer to each other, not for rich text editors The workspaces-pages-blocks tree structure.
The issue is planned to be completed before May, and the pre-requisites are: #238

**Comment by doodlewind** [comment]
Let's tracked in https://github.com/toeverything/AFFiNE/issues/1556
