### ISSUE TITLE
Update the Self-Hosted Docker Images​

### ISSUE THREAD

**Issue by EzxD** [toeverything/OctoBase#457]
### Description

I wanted to try the Selfhosted Version but then i saw the last update of the image is months ago. 
Would be great to update the images to the normal releases. Or am I missing something?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by darkskygit** [comment]
> Meanwhile, is there a Dockerfile and instructions somewhere so we can build ourselves? Or do we have to wait for the milestone?

You can refer to the following Dockerfile, but please note that the server is currently only for debugging purposes:

https://github.com/toeverything/OctoBase/blob/master/.github/deployment/Dockerfile-cloud

You need to fill in the necessary environment variables yourself to make it available. Meanwhile, we plan to provide ready-to-use Docker containers in 1-2 months to facilitate everyone's use.

**Comment by omarcostahamido** [comment]
Hi @darkskygit @xell i would like to ask about this `ready-to-use Docker container` since it's been half a since last post, and I just noticed that, on the new website, mentions to the self-host mode were totally removed.
I am a supporter of AFFiNE and I would really love to see you deliver on what you promissed.
Thank you very much for your work and careful attention to this 🙏

**Comment by darkskygit** [comment]
> Hi @darkskygit @xell i would like to ask about this `ready-to-use Docker container` since it's been half a since last post, and I just noticed that, on the new website, mentions to the self-host mode were totally removed. I am a supporter of AFFiNE and I would really love to see you deliver on what you promissed. Thank you very much for your work and careful attention to this 🙏

Thank you for your attention. The code related to the AFFiNE server and self-hosted codes has been moved to the affine repository, which will focus on becoming a CRDT library.
In the past six months, we are improving AFFiNE to make it more stable. We will recently release a better version 0.10 and plan to provide out-of-the-box self-hosted images between versions 0.10-0.12.

**Comment by omarcostahamido** [comment]
thank you for your answer @darkskygit .
Since I was not able to find the issue on the other repo, i went ahead and created it myself.
Fingers crossed this can see the light of day sometime in the near future.
Best

**Comment by EYHN** [comment]
Tracked in https://github.com/toeverything/AFFiNE/issues/5069
